version: '2.3'

services:
  base:
    build:
      context: .
      target: development
    volumes:
      - ./packages/api/bootstrap:/api/bootstrap
      - ./packages/api/middlewares:/api/middlewares
      - ./packages/api/schema/:/api/schema
      - ./packages/api/server.js:/api/server.js
      - ./packages/api/.babelrc:/api/.babelrc

  database:
    image: mongo:4.0.2
    healthcheck:
      test: echo 'db.runCommand("ping").ok | mongo localhost:27017 --quiet'
      interval: 5s
      retries: 5
    expose:
      - 27017

  api:
    extends: base
    ports:
      - 4004:4004
    env_file: ./packages/api/.env
    healthcheck:
      test: curl --silent --fail localhost:4004/.well-known/apollo/server-health || exit 1
      interval: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy

  test-integration:
    extends: base
    volumes:
      - ./packages/api/tests:/api/tests
    command: yarn test:integration
    depends_on:
      api:
        condition: service_healthy
